[project]
name = "workflows-ai"
version = "0.1.0"
description = "AI-powered workflows"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "black",
    "mypy",
    "ruff"
] 